name: README magik

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */1 * * *"

permissions:
  contents: write

jobs:
  magik:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Generate README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python generate_readme.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          if ! git diff --staged --quiet; then
            git commit -m "🪄 Sprinkle the README with some magik"
            git push
          else
            echo "README.md is already up-to-date."
          
          fi